### ISSUE TITLE
Consider using external source-maps

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/pack#30]
Currently, the source-map is always made inline with the built script. This was done largely for ease-of-implementation, especially when you can't predict if the user is using stdout or not.

The main benefits would be:

 * Shrinking the size of the built itself (granted it's in a new file, but the browser can download the map in parallel afaik)
 * Allowing source maps to continue to be used even in production (since the browser probably doesn't download a source map unless the console/debugger is opened, right?)

The first complication I can think of is how this would be implemented in a middleware or something like duo-serve. Since now we have another file that isn't the built entry file that would need to be served up, it wouldn't be a simple 1-1 route anymore. (would there be a flag or another method altogether for the source map?)

**Comment by markreg** [comment]
Has a patch been written for this?

**Comment by stephenmathieson** [comment]
#35 ;)

**Comment by dominicbarnes** [comment]
Oh, that other PR doesn't add external source maps (I plan on working on that today though!)

**Comment by stephenmathieson** [comment]
haha whoops
