### ISSUE TITLE
wrong relative url in windows

### ISSUE THREAD

**Issue by imyelo** [duojs/pack#31]
etc:
```javascript
body {
  background-image: url('images/logo.svg');
}
```

compile in windows:
```javascript
body {
  background-image: url(..\components\foobar-logo@master\images\logo.svg);
}
```

open in chrome will get an error:
>  Failed to load  http://localhost:8080/dest/..%0Componentsfoobar-logo@masterimageslogo.svg resource: the server responded with a status of 404 (Not Found)

**Comment by dominicbarnes** [comment]
You should be using a relative path, otherwise it looks like a repo you are trying to include.

Try switching to `./images/logo.svg`, that should solve the problem. Feel free to re-open if that's not enough.
