### ISSUE TITLE
standalone() + development(true) causes "Uncaught SyntaxError: Unexpected end of input"

### ISSUE THREAD

**Issue by poying** [duojs/pack#38]
`);` should not in the source map comment, it should at the next line.

![2015-03-11 12 03 32](https://cloud.githubusercontent.com/assets/1190072/6590215/d9b01886-c7e7-11e4-8034-5ec86471cb38.png)

![2015-03-11 12 03 04](https://cloud.githubusercontent.com/assets/1190072/6590216/d9b08ab4-c7e7-11e4-848f-caaf2a0de520.png)

**Comment by dominicbarnes** [comment]
Ah yes, I can see the problem. I'll try and resolve this as soon as possible. Thanks for the heads-up! (feel free to submit a PR if you get started ahead of me)

**Comment by poying** [comment]
@dominicbarnes Before v2.0.0, we can fix this issue easily by modifying `lib/js/sourcemap.js`, but now, I can't figure out whether this issue exists or not.
